### PR TITLE
Add option: `IgnoreExternalBrokenLinks`

### PR DESCRIPTION
**Pull request by abhishalya**
Do let me know if it is useful, we particularly required this while checking links for [julialang.org](https://julialang.org) site which has a large number of links.

I'll add tests and docs soon, if this idea looks good enough.

Closes https://github.com/wjdp/htmltest/issues/139

cc @wjdp

### CODE REVIEW

**Comment by wjdp** [comment]
@abhishalya Saw your issue this morning. We've this exact problem on a site I help maintain, :+1: on the feature from me!

**Comment by wjdp** [comment]
I can see this is marked as WIP but thought I'd mention:

- This will need tests
- I'm unsure on the option name `AllowExternalLinksToFail`, we've no other options with the prefix "Allow". "Ignore" is quite prevalent but not sure if this feels right. If the other usages of "Ignore" imply demoting errors to warnings this fits, elsewise "Allow" may want adding for this meaning. I've a feeling the "Ignore" prefix has both "ignore completly" and "demote to warning" implementations, would be worth clearing these up.

**Comment by abhishalya** [comment]
@wjdp I agree. How about `IgnoreExternalBrokenLinks`?

**Comment by abhishalya** [comment]
@wjdp I've added the tests, can you have a look again :)

**Comment by abhishalya** [comment]
@wjdp Any update on this one?

**Comment by wjdp** [comment]
Sorry about delay on this!

**Comment by abhishalya** [comment]
No problem, thanks for the merge :)

**Pull request merged**
