### PR TITLE
Apply IgnoreURLs regexs to internal and file URLs too

### LINKED ISSUE #109: IgnoreURLs fails if URL given is not the domain
`IgnoreURLs` only seems to ignore matching _domains_. Given the name, I'm guessing it should also be able to ignore both `www.anydomain.com/folder1/none.html` and `file:///C:///stupidfolder/folder3/none.html`

with a setting like:
```
IgnoreURLs:
- "none.html"
```

### PR DESCRIPTION
**Pull request by chalin**
- Closes #109
- Solves the original request of #168

### CODE REVIEW

**Comment by chalin** [comment]
Friendly ping @wjdp - it has been two months now. Thanks.

**Comment by chalin** [comment]
4 month ping @wjdp - do you have an ETA for when this PR is likely to be reviewed? Thanks.

**Comment by felixminom** [comment]
@wjdp will be good to have this reviewed and merged. Facing the same issue :/

**Comment by wjdp** [comment]
Hi @chalin, very sorry for delay on this. Reading through the issues and MRs around this it would seem to make more sense to combine all ignoring into the `IgnoreURLs` option and deprecate the `IgnoreInternalURLs` option as it's very specific and can be handled just with `IgnoreURLs`, will do some testing and look to get this merged.

**Comment by chalin** [comment]
Great! Thanks for the heads up. Looking forward to this new capability.

**Pull request merged**
