### PR TITLE
Adding IgnoreSSLVerify option

### PR DESCRIPTION
**Pull request by jgazeau**

### CODE REVIEW

**Comment by jgazeau** [comment]
Patch to add IgnoreSSLVerify option (issue #112 )

**Comment by wjdp** [comment]
PR makes sense, simple and effective! Unsure why the tests are failing, having a quick look now.

I've tweaked the README wording and would be nice to have a test case for this option.

**Comment by wjdp** [comment]
Is failing on master as well, some package or the Travis environment must have changed. Very odd.

**Comment by jgazeau** [comment]
It seems that they changed something in the golan url_test.go and add a new check for special char (check : https://github.com/golang/go/commit/829c5df58694b3345cb5ea41206783c8ccf5c3ca#diff-6f43cc724ae52e4acba8855ce391e144)
I agree that it would be nice to have a test to check the IgnoreSSLVerify option. I'll check this and see how to do it.

**Comment by wjdp** [comment]
@jgazeau Can you rebase this on master?

**Comment by jgazeau** [comment]
@wjdp Rebase done.
Haven't checked to implement a test for this option yet.

**Comment by wjdp** [comment]
Thanks, I'll hold off merging until you've done a test case.

**Comment by jgazeau** [comment]
@wjdp,

I add two test cases (TestSelfSignedLink and TestSelfSignedLinkIgnoreSSLVerify) in the check-link_test.go.
- TestSelfSignedLink is checking if a link with a selfsigned certificate is returning an error with the IgnoreSSLVerify=false
- TestSelfSignedLinkIgnoreSSLVerify is checking if a link with a selfsigned certificate is not returning any error with the IgnoreSSLVerify=true

For the test I use the self-signed link of https://badssl.com/.

FYI: To be sure, I run one pipeline to check the job is throwing errors by swaping the IgnoreSSLVerify boolean value :
https://travis-ci.org/jgazeau/htmltest/jobs/524849941 (Line 764)

**Comment by wjdp** [comment]
@jgazeau Whoops, sorry I missed your last comment. Thanks for the PR!

**Pull request merged**
