### PR TITLE
add IgnoreHTTPS option

### LINKED ISSUE #191: exceptions for EnforceHTTPS
`EnforceHTTPS` has already helped me discover several instances where I point to the HTTP version of an external site when there's a functioning HTTPS version. Unfortunately, a few sites are only available with HTTP, but I don't want to add them to `IgnoreURLs` because I still do want to check them. Can we add a separate exception list for `EnforceHTTPS`?

I'm willing to open a PR but I wanted to run it by you first.

### PR DESCRIPTION
**Pull request by kylrth**
Let me know if you want me to rename or rearrange anything!

closes #191

### CODE REVIEW

**Comment by kylrth** [comment]
That test was broken when I opened the repo, btw

**Comment by wjdp** [comment]
@kylrth Yep spotted that too, if you merge in master it should be fixed.

**Review by wjdp — APPROVED** [review]
Looks good, thanks for the PR!

**Comment by wjdp** [comment]
Will also close #42

**Comment by wjdp** [comment]
Actually not much point messing about, will just merge and check locally

**Pull request merged**
